name = "canvas-game-template"
main = "src/worker.js"
compatibility_date = "2024-12-13"

[env.production]
name = "canvas-game-template"

[env.staging]
name = "canvas-game-template-staging"

# Static Assets configuration for SPA
[assets]
directory = "dist"
